require("config.lazy")
require("config.remap")
require("config.colorscheme")
require("config.term")
require("config.lsp")
require("config.makeprg")
require("config.telescope")
require("config.oilsetup")
